export { default as UserLayout } from './UserLayout'
export { default as Home } from './Home'
export { default as About } from './About'
export { default as Videos } from './Videos'
export { default as Contact } from './Contact'
export { default as Favorites } from './Favorites'
export { default as SingleVideo } from './SingleVideo'
export { default as LiveVideo } from './LiveVideo'
